/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ua.com.dzlobenets.statistics;

import ua.com.dzlobenets.stat.lib.MeasureOfCentralTendency;

import java.util.Arrays;
import java.util.List;

public class App {

    public static void main(String[] args) {
        final List<? extends Number> numbers = Arrays.asList(33.54, 545, 44.56, 453, 435, 55, 44, 33, 33);
        Number mode = MeasureOfCentralTendency.mode(numbers);
        System.out.println("Mode of: " + numbers);
        System.out.println(" " + mode);
    }
}
