/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ua.com.dzlobenets.statistics;

import ua.com.dzlobenets.stat.lib.Statistics;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Statistics.test();
    }
}
